[workspace]
members = [
    "crates/PROJECT_NAME",
    "crates/pane",
    "crates/docking",
    "crates/panels",
    "crates/modals",
    "crates/theme",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

# Use official crates.io release of gpui.
gpui = { version = "*" }
